export type Field={key:string;label:string;type?:string;required?:boolean;options?:string[]}
export type Resource={label:string;table?:string;fields:Field[];order?:string;descending?:boolean}
const f=(key:string,label:string,type='text',required=false):Field=>({key,label,type,required})
const status:Field={key:'status',label:'공개 상태',type:'select',options:['draft','published','archived']}
const common=[f('slug','주소 이름 (영문·숫자·하이픈)'),status,f('sort_order','표시 순서','number')]
export const resources:Record<string,Resource>={
series:{label:'시리즈·일정',table:'series',order:'starts_at',fields:[f('title','시리즈명','text',true),f('subtitle','한 줄 소개'),f('description','상세 설명','textarea'),f('starts_at','시작','datetime-local',true),f('ends_at','종료','datetime-local',true),f('venue_name','장소'),f('venue_address','주소'),f('map_url','지도 URL','url'),f('poster_url','가로 배너','image'),f('mobile_poster_url','모바일 포스터','image'),f('notice','안내 사항','textarea'),f('document_url','첨부 PDF','file'),...common]},
events:{label:'이벤트',table:'events',order:'starts_at',fields:[f('title','이벤트명','text',true),f('series_id','소속 시리즈','series',true),f('event_number','이벤트 번호','number'),f('starts_at','시작','datetime-local',true),f('category','경기 종목'),f('description','상세 안내','textarea'),f('late_registration','접수 마감'),f('registration_url','참가 안내 URL','url'),f('structure_url','첨부 PDF','file'),f('poster_url','포스터','image'),f('banner_url','배너','image'),f('thumbnail_url','썸네일','image'),...common]},
news:{label:'뉴스·인터뷰',table:'articles',order:'published_at',descending:true,fields:[f('title','기사 제목','text',true),f('excerpt','요약','textarea'),{key:'category',label:'분류',type:'select',options:['ANNOUNCEMENT','SERIES','INTERVIEW','FIELD NOTES','PLAYER PORTRAIT','KSOP JOURNAL']},f('body','기사 본문','textarea',true),f('cover_url','대표 이미지','image'),f('author','작성자'),f('published_at','게시 일시','datetime-local',true),...common]},
players:{label:'선수·랭킹',table:'players',order:'points',descending:true,fields:[f('name','선수명','text',true),f('display_name','표시명'),f('country','국가'),f('portrait_url','사진','image'),f('bio','소개','textarea'),f('points','공개 시즌 점수','number'),f('rank','공개 순위','number'),f('titles','우승 수','number'),f('final_tables','파이널 수','number'),...common]},
results:{label:'선수 경기 기록',table:'player_results',order:'event_date',descending:true,fields:[f('player_id','선수','players',true),f('event_id','이벤트','events'),f('event_name','대회명','text',true),f('event_date','경기 날짜','date',true),f('position','순위','number',true),f('field_size','참가 선수 수','number',true),status]},
about:{label:'회사 소개·대표 인사·연혁',table:'about_pages',fields:[f('title','제목','text',true),f('eyebrow','구분'),f('excerpt','요약','textarea'),f('body','본문','textarea',true),f('cover_url','이미지','image'),...common]},
videos:{label:'영상·숏츠',fields:[f('title','영상 제목','text',true),{key:'category',label:'분류',type:'select',options:['highlights','full','shorts','behind']},f('url','YouTube URL','youtube',true),f('image','썸네일','image'),f('description','설명','textarea'),...common]},
partners:{label:'파트너',fields:[f('title','브랜드명','text',true),f('image','투명 로고','image',true),f('url','공식 홈페이지','url'),f('description','회사 소개','textarea'),...common]}}
export const statusLabels:Record<string,string>={draft:'비공개 초안',published:'공개',archived:'보관'}
export function safeUrl(v:unknown){if(typeof v!=='string'||!v.trim())return '';const s=v.trim();if(/^\/(?!\/)/.test(s)&&!/[\\\r\n]/.test(s))return s;try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?s:''}catch{return ''}}
export function validateRecord(resource:string,raw:Record<string,unknown>){const out:Record<string,any>={};for(const f of resources[resource].fields){let v=raw[f.key];if(v===undefined){if(f.required)throw Error(f.label+'을 입력하세요.');continue}if(f.type==='number'){v=Number(v||0);if(!Number.isSafeInteger(v)||Number(v)<0)throw Error(f.label+'을 확인하세요.')}else{v=String(v??'').trim();if(f.required&&!v)throw Error(f.label+'을 입력하세요.');if(String(v).length>(f.type==='textarea'?100000:2000))throw Error('내용이 너무 깁니다.');if(['url','image','file','youtube'].includes(f.type||'')&&v&&!safeUrl(v))throw Error('주소를 확인하세요.');if(f.type==='youtube'&&v&&!/^(www\.|m\.)?(youtube\.com|youtu\.be)$/.test(new URL(String(v)).hostname))throw Error('YouTube 주소가 필요합니다.');if(f.type==='select'&&!f.options?.includes(String(v)))throw Error('분류를 확인하세요.');if(['date','datetime-local'].includes(f.type||'')&&v){const d=new Date(String(v));if(!Number.isFinite(d.getTime()))throw Error('날짜를 확인하세요.');if(f.type==='datetime-local')v=d.toISOString()}if(['series','players','events'].includes(f.type||'')){if(v&&!/^[0-9a-f-]{36}$/i.test(String(v)))throw Error('연결 항목을 선택하세요.');if(!v)v=null}}out[f.key]=v}if(out.slug&&!/^[a-z0-9][a-z0-9-]{0,149}$/.test(out.slug))throw Error('주소 이름은 영문 소문자·숫자·하이픈만 가능합니다.');if(resource==='series'&&out.ends_at<out.starts_at)throw Error('종료 일시를 확인하세요.');if(resource==='results'&&(out.position<1||out.field_size<2||out.position>out.field_size))throw Error('순위와 인원을 확인하세요.');return out}
