import type { EventItem, Language, NewsItem, PlayerItem, SiteContent } from './types'

const eventNames = [
  'NLH Poker Players Championship / Day 1A',
  'NLH Warm-up',
  'NLH Good Game 500',
  'PLO Kick-off',
  'NLH Deepstack',
  'PLO Night',
  'NLH Bigstack Hyper',
  'Satellite to #25 NLH Good Game 1000',
  'Main Event Day 1',
  'High Roller Championship',
]

const eventTypes = ['NLH', 'NLH', 'NLH', 'PLO', 'NLH', 'PLO', 'NLH', 'SATELLITE', 'MAIN EVENT', 'HIGH ROLLER'] as const

export function createSeedEvents(): EventItem[] {
  return Array.from({ length: 100 }, (_, index) => {
    const day = Math.min(22, 17 + Math.floor(index / 17))
    const name = eventNames[index % eventNames.length]
    const type = eventTypes[index % eventTypes.length]

    return {
      id: `event-${index + 1}`,
      date: `NOV ${day}`,
      dayLabel: `DAY ${index + 1}`,
      name: `${name} #${index + 1}`,
      type,
      buyInType: 'INVITATION',
      buyIn: ['₩8,000', '₩10,000', '₩12,000', '₩25,000', '₩50,000'][index % 5],
      gtd: ['₩8,000', '₩10,000', '₩12,000', '₩25,000', '₩50,000'][index % 5],
      startingChips: 15000,
      lateReg: 'LEVEL 8',
      levelTime: '15 MIN',
      blindStructure: [
        { level: 1, small: 100, big: 200, ante: 200 },
        { level: 2, small: 200, big: 400, ante: 400 },
      ],
      published: true,
      posterUrl: '',
      bannerUrl: '',
      thumbnailUrl: '',
    }
  })
}

export const seedPlayers: PlayerItem[] = [
  { id: 'jun-hyuk-lee', dbId: '', rank: 1, name: 'JUN-HYUK LEE', country: 'KR', earnings: '₩ 218,400,000', portrait: '/images/ksop-player-1.png', bio: 'KSOP ranking leader known for deep runs and disciplined late-game decisions.', published: true },
  { id: 'daniel-lim', dbId: '', rank: 2, name: 'DANIEL LIM', country: 'KR', earnings: '₩ 164,800,000', portrait: '/images/ksop-player-2.png', published: true },
  { id: 'min-seok-kim', dbId: '', rank: 3, name: 'MIN-SEOK KIM', country: 'KR', earnings: '₩ 129,500,000', portrait: '/images/ksop-player-3.png', published: true },
  { id: 'alex-park', dbId: '', rank: 4, name: 'ALEX PARK', country: 'US', earnings: '₩ 98,200,000', published: true },
  { id: 'so-yeon-han', dbId: '', rank: 5, name: 'SO-YEON HAN', country: 'KR', earnings: '₩ 82,600,000', published: true },
  { id: 'ryan-choi', dbId: '', rank: 6, name: 'RYAN CHOI', country: 'CA', earnings: '₩ 74,300,000', published: true },
  { id: 'jae-won-park', dbId: '', rank: 7, name: 'JAE-WON PARK', country: 'KR', earnings: '₩ 68,900,000', published: true },
  { id: 'michael-kim', dbId: '', rank: 8, name: 'MICHAEL KIM', country: 'US', earnings: '₩ 59,400,000', published: true },
  { id: 'hye-jin-seo', dbId: '', rank: 9, name: 'HYE-JIN SEO', country: 'KR', earnings: '₩ 51,200,000', published: true },
  { id: 'david-kang', dbId: '', rank: 10, name: 'DAVID KANG', country: 'AU', earnings: '₩ 46,800,000', published: true },
]

export const seedNews: NewsItem[] = [
  {
    slug: 'how-a-final-table-finds-its-rhythm',
    category: 'FIELD NOTES',
    date: '12.09.25',
    title: 'How a final table finds its rhythm',
    excerpt: 'Inside the tempo shifts that define a championship final table.',
    body: 'The final table rarely announces itself with fireworks. Instead, it settles into a rhythm — a sequence of small decisions that compound into a defining arc for the entire series.',
    published: true,
  },
  {
    slug: 'jun-hyuk-lee-playing-the-long-game',
    category: 'PLAYER PORTRAIT',
    date: '08.09.25',
    title: 'JUN-HYUK LEE: PLAYING THE LONG GAME',
    excerpt: 'A portrait of the current KSOP ranking leader.',
    body: 'JUN-HYUK LEE built his ranking through consistency rather than spectacle — patient lines, selective aggression, and a reputation for reading pressure points late in tournaments.',
    published: true,
  },
  {
    slug: 'seoul-after-dark-the-city-around-the-felt',
    category: 'KSOP JOURNAL',
    date: '01.09.25',
    title: 'Seoul, after dark: the city around the felt',
    excerpt: 'The city outside the arena becomes part of the KSOP experience.',
    body: 'When the cards pause, Seoul keeps moving. From Grand Hyatt to the late-night streets, the city offers its own rhythm to players between sessions.',
    published: true,
  },
]

export const seedContent: SiteContent = {
  heroImage: '/images/ksop-hero-arena.png',
  logoBlack: '/images/ksop-light-approved.png',
  logoWhite: '/images/ksop-dark-approved.png',
  seriesDate: '17 NOV 2026',
  seriesVenue: 'SEOUL · GRAND HYATT',
  seriesGtd: '₩1,500,000,000 GTD',
  countdownDays: 75,
  introTitle: 'More than\na tournament.',
  introBody: "KSOP is a meeting place for Korea's sharpest minds, boldest plays, and most unforgettable stories.",
  imageBreakLabel: 'THE TABLE IS SET',
  imageBreakTitle: 'See you',
  imageBreakEmphasis: 'at the felt.',
  copy: {
    EN: {
      ticker: '[LIVE NEXT EVENT] SEOUL GRAND PRIX · COUNTDOWN: 75D : 00H : 00M : 00S',
      nav: ['SCHEDULE', 'EVENT', 'RANKING', 'NEWS', 'ABOUT'],
      eyebrow: 'THE KOREA SERIES OF POKER · 2026',
      hero: 'THE PINNACLE OF LIVE POKER',
      intro: 'Where discipline meets instinct. A new standard for live poker in Korea.',
      register: 'REGISTER NOW',
      explore: 'EXPLORE EVENTS',
      guaranteed: 'GUARANTEED PRIZE POOL',
      invitation: 'INVITATION',
      stack: 'STARTING STACK',
      reg: 'REGISTRATION',
      schedule: 'EVENTS',
      ranking: 'TOP PLAYERS',
      news: 'INSIDE THE STORY.',
      follow: 'FOLLOW THE SERIES',
      buyin: 'BUY-IN',
      seatReserved: 'SEAT RESERVED',
      viewEvent: 'View event',
      viewEvents: 'View events',
      viewAllEvents: 'View all events',
      fullRanking: 'Full ranking',
      viewProfile: 'View profile',
      allNews: 'All news',
      readStory: 'Read the story',
      registerShort: 'Register',
      searchPlayer: 'Search player',
      showing: 'SHOWING {shown} OF {total} EVENTS',
      noEvents: 'NO EVENTS MATCH THE SELECTED FILTERS',
      clearFilters: 'CLEAR FILTERS',
      showMore: 'SHOW MORE ({remaining} REMAINING)',
      allDates: 'ALL DATES',
      openEvent: 'Open event page',
      seriesLabel: '01 / THE SERIES',
      scheduleLabel: '02 / UPCOMING SERIES',
      rankingLabel: '03 / PLAYER RANKING',
      newsLabel: '04 / FROM THE SERIES',
      introTitle: 'More than',
      introEmphasis: 'a tournament.',
      footerLine1: "Korea's premier live poker series.",
      footerLine2: 'Designed for the game.',
      countdown: 'COUNTDOWN',
      posterMonth: 'NOVEMBER',
      factChips: 'STARTING CHIPS',
      factLate: 'LATE REG.',
      factLevel: 'LEVEL TIME',
      factType: 'TYPE',
      factBuyin: 'BUY-IN',
      eventDetail: 'EVENT DETAIL',
      eventStatus: 'EVENT STATUS',
      regStatus: 'REGISTRATION STATUS',
      statusPending: 'STATUS PENDING',
      regPending: 'REGISTRATION PENDING',
      blindStructure: 'BLIND STRUCTURE',
      blindLevel: 'LEVEL',
      blindSmallBig: 'SMALL / BIG',
      blindAnte: 'ANTE',
      resultLabel: 'RESULT',
      liveLabel: 'LIVE',
      resultPending: 'RESULT DATA PENDING',
      livePending: 'LIVE DATA PENDING',
      backToSchedule: 'Back to schedule',
      backToRanking: 'Back to ranking',
      backToNews: 'Back to news',
      backToAbout: 'Back to about',
      backHome: 'BACK TO HOME ↗',
      backToScheduleArrow: 'BACK TO SCHEDULE ↗',
      playerProfile: 'PLAYER PROFILE',
      rankLabel: 'RANK',
      countryLabel: 'COUNTRY',
      earningsLabel: 'EARNINGS',
      bioPending: 'Player profile details will be managed from the admin panel.',
      resultHistory: 'RESULT / TOURNAMENT HISTORY',
      noNews: 'NO PUBLISHED NEWS',
      newsNotes: 'NEWS · NOTES · PORTRAITS',
      exploreSchedule: 'Explore the schedule',
      theSeries: 'THE SERIES',
      theVenue: 'THE VENUE',
      seriesDetail: '01 / THE SERIES · DETAIL',
      venueLabel: 'VENUE',
      dateLabel: 'DATE',
      guaranteedLabel: 'GUARANTEED',
      contentPending: 'CONTENT PENDING',
      eventList: 'EVENT LIST',
      schedulePending: 'EVENT SCHEDULE PENDING',
      seriesWord: 'SERIES',
      dateRangeLabel: 'DATE RANGE',
      eventsWord: 'EVENTS',
      tba: 'TBA',
      scheduleKicker: '01 / SCHEDULE · SERIES',
    },
    KR: {
      ticker: '[LIVE NEXT EVENT] 서울 그랑프리 · 카운트다운: 14일 : 08시간 : 42분 : 12초',
      nav: ['일정', '이벤트', '랭킹', '뉴스', 'KSOP 소개'],
      eyebrow: '코리아 시리즈 오브 포커 · 2026',
      hero: '라이브 포커의 정점',
      intro: '절제와 본능이 만나는 곳. 한국 라이브 포커의 새로운 기준.',
      register: '지금 등록하기',
      explore: '이벤트 보기',
      guaranteed: '보장 상금',
      invitation: 'INVITATION',
      stack: '스타팅 스택',
      reg: '등록 마감',
      schedule: '주요 이벤트',
      ranking: '탑플레이어',
      news: '시리즈의 이야기.',
      follow: '시리즈 팔로우',
      buyin: '바이인',
      seatReserved: '좌석 예약됨',
      viewEvent: '이벤트 보기',
      viewEvents: '이벤트 보기',
      viewAllEvents: '모든 이벤트 보기',
      fullRanking: '전체 랭킹 보기',
      viewProfile: '프로필 보기',
      allNews: '모든 뉴스',
      readStory: '이야기 읽기',
      registerShort: '등록',
      searchPlayer: '선수 검색',
      showing: '전체 {total}개 중 {shown}개 표시',
      noEvents: '조건에 맞는 이벤트가 없습니다',
      clearFilters: '필터 초기화',
      showMore: '더 보기 ({remaining}개 남음)',
      allDates: '전체 날짜',
      openEvent: '이벤트 페이지 열기',
      seriesLabel: '01 / 시리즈',
      scheduleLabel: '02 / 예정된 시리즈',
      rankingLabel: '03 / 선수 랭킹',
      newsLabel: '04 / 시리즈 소식',
      introTitle: '토너먼트를',
      introEmphasis: '넘어서.',
      footerLine1: '한국 최고의 라이브 포커 시리즈.',
      footerLine2: '게임을 위해 디자인되었습니다.',
      countdown: '카운트다운',
      posterMonth: '11월',
      factChips: '스타팅 칩',
      factLate: '레이트 레지',
      factLevel: '레벨 시간',
      factType: '타입',
      factBuyin: '바이인',
      eventDetail: '이벤트 상세',
      eventStatus: '이벤트 상태',
      regStatus: '등록 상태',
      statusPending: '상태 업데이트 예정',
      regPending: '등록 오픈 예정',
      blindStructure: '블라인드 구조',
      blindLevel: '레벨',
      blindSmallBig: '스몰 / 빅',
      blindAnte: '앤티',
      resultLabel: '결과',
      liveLabel: '라이브',
      resultPending: '결과 데이터 업데이트 예정',
      livePending: '라이브 데이터 업데이트 예정',
      backToSchedule: '일정으로 돌아가기',
      backToRanking: '랭킹으로 돌아가기',
      backToNews: '뉴스로 돌아가기',
      backToAbout: '소개로 돌아가기',
      backHome: '홈으로 돌아가기 ↗',
      backToScheduleArrow: '일정으로 돌아가기 ↗',
      playerProfile: '선수 프로필',
      rankLabel: '순위',
      countryLabel: '국가',
      earningsLabel: '상금',
      bioPending: '선수 프로필 상세 정보는 관리자 패널에서 관리됩니다.',
      resultHistory: '결과 / 토너먼트 기록',
      noNews: '공개된 뉴스가 없습니다',
      newsNotes: '뉴스 · 노트 · 포트레이트',
      exploreSchedule: '일정 살펴보기',
      theSeries: '시리즈',
      theVenue: '장소',
      seriesDetail: '01 / 시리즈 · 상세',
      venueLabel: '장소',
      dateLabel: '날짜',
      guaranteedLabel: '개런티',
      contentPending: '콘텐츠 업데이트 예정',
      eventList: '이벤트 목록',
      schedulePending: '이벤트 일정 업데이트 예정',
      seriesWord: '시리즈',
      dateRangeLabel: '기간',
      eventsWord: '이벤트',
      tba: '미정',
      scheduleKicker: '01 / 일정 · 시리즈',
    },
    JP: {
      ticker: '[LIVE NEXT EVENT] ソウル・グランプリ · カウントダウン: 14日 : 08時間 : 42分 : 12秒',
      nav: ['スケジュール', 'イベント', 'ランキング', 'ニュース', 'KSOPについて'],
      eyebrow: 'コリアシリーズオブポーカー · 2026',
      hero: 'ライブポーカーの頂点',
      intro: '規律と本能が出会う場所。韓国ライブポーカーの新基準。',
      register: '今すぐ登録',
      explore: 'イベントを見る',
      guaranteed: '保証賞金',
      invitation: 'INVITATION',
      buyin: 'バイイン',
      stack: 'スターティングスタック',
      reg: '登録期間',
      schedule: '主要イベント',
      ranking: 'トッププレイヤー',
      news: 'シリーズの物語。',
      follow: 'シリーズをフォロー',
      seatReserved: '予約済み',
      viewEvent: 'イベントを見る',
      viewEvents: 'イベントを見る',
      viewAllEvents: 'すべてのイベントを見る',
      fullRanking: '全ランキングを見る',
      viewProfile: 'プロフィールを見る',
      allNews: 'すべてのニュース',
      readStory: '記事を読む',
      registerShort: '登録',
      searchPlayer: '選手を検索',
      showing: '{total}件中{shown}件を表示',
      noEvents: '条件に合うイベントがありません',
      clearFilters: 'フィルターをクリア',
      showMore: 'さらに表示（残り{remaining}件）',
      allDates: 'すべての日程',
      openEvent: 'イベントページを開く',
      seriesLabel: '01 / シリーズ',
      scheduleLabel: '02 / 開催予定シリーズ',
      rankingLabel: '03 / プレイヤーランキング',
      newsLabel: '04 / シリーズより',
      introTitle: 'トーナメントを',
      introEmphasis: '超えて。',
      footerLine1: '韓国最高峰のライブポーカーシリーズ。',
      footerLine2: 'ゲームのためにデザインされました。',
      countdown: 'カウントダウン',
      posterMonth: '11月',
      factChips: 'スターティングチップ',
      factLate: 'レイトレジ',
      factLevel: 'レベル時間',
      factType: 'タイプ',
      factBuyin: 'バイイン',
      eventDetail: 'イベント詳細',
      eventStatus: 'イベントステータス',
      regStatus: '登録ステータス',
      statusPending: 'ステータス未定',
      regPending: '登録受付前',
      blindStructure: 'ブラインドストラクチャー',
      blindLevel: 'レベル',
      blindSmallBig: 'スモール / ビッグ',
      blindAnte: 'アンティ',
      resultLabel: 'リザルト',
      liveLabel: 'ライブ',
      resultPending: 'リザルトは後日公開',
      livePending: 'ライブ配信は後日公開',
      backToSchedule: 'スケジュールに戻る',
      backToRanking: 'ランキングに戻る',
      backToNews: 'ニュースに戻る',
      backToAbout: '紹介に戻る',
      backHome: 'ホームに戻る ↗',
      backToScheduleArrow: 'スケジュールに戻る ↗',
      playerProfile: '選手プロフィール',
      rankLabel: 'ランク',
      countryLabel: '国籍',
      earningsLabel: '獲得賞金',
      bioPending: '選手プロフィールの詳細は管理パネルで管理されます。',
      resultHistory: 'リザルト / トーナメント履歴',
      noNews: '公開中のニュースがありません',
      newsNotes: 'ニュース · ノート · ポートレート',
      exploreSchedule: 'スケジュールを見る',
      theSeries: 'シリーズ',
      theVenue: '会場',
      seriesDetail: '01 / シリーズ · 詳細',
      venueLabel: '会場',
      dateLabel: '日程',
      guaranteedLabel: 'ギャランティ',
      contentPending: 'コンテンツ準備中',
      eventList: 'イベントリスト',
      schedulePending: 'イベントスケジュールは後日公開',
      seriesWord: 'シリーズ',
      dateRangeLabel: '開催期間',
      eventsWord: 'イベント',
      tba: '未定',
      scheduleKicker: '01 / スケジュール · シリーズ',
    },
    CN: {
      ticker: '[LIVE NEXT EVENT] 首尔大奖赛 · 倒计时: 14天 : 08小时 : 42分 : 12秒',
      nav: ['赛程', '赛事', '排名', '新闻', '关于KSOP'],
      eyebrow: '韩国扑克系列赛 · 2026',
      hero: '现场扑克的巅峰',
      intro: '纪律与本能相遇的地方。韩国现场扑克的新标准。',
      register: '立即报名',
      explore: '查看赛事',
      guaranteed: '保证奖金',
      invitation: 'INVITATION',
      buyin: '买入',
      stack: '起始筹码',
      reg: '报名截止',
      schedule: '主要赛事',
      ranking: '顶尖选手',
      news: '系列故事。',
      follow: '关注赛事',
      seatReserved: '已预留座位',
      viewEvent: '查看赛事',
      viewEvents: '查看赛事',
      viewAllEvents: '查看所有赛事',
      fullRanking: '查看完整排名',
      viewProfile: '查看选手资料',
      allNews: '所有新闻',
      readStory: '阅读报道',
      registerShort: '报名',
      searchPlayer: '搜索选手',
      showing: '共{total}场赛事，显示{shown}场',
      noEvents: '没有符合筛选条件的赛事',
      clearFilters: '清除筛选',
      showMore: '显示更多（还剩{remaining}场）',
      allDates: '所有日期',
      openEvent: '打开赛事页面',
      seriesLabel: '01 / 系列赛',
      scheduleLabel: '02 / 即将到来的系列赛',
      rankingLabel: '03 / 选手排名',
      newsLabel: '04 / 系列动态',
      introTitle: '超越',
      introEmphasis: '锦标赛。',
      footerLine1: '韩国顶级现场扑克系列赛。',
      footerLine2: '为比赛而设计。',
      countdown: '倒计时',
      posterMonth: '11月',
      factChips: '起始筹码',
      factLate: '延迟报名',
      factLevel: '级别时长',
      factType: '类型',
      factBuyin: '买入',
      eventDetail: '赛事详情',
      eventStatus: '赛事状态',
      regStatus: '报名状态',
      statusPending: '状态待定',
      regPending: '报名尚未开放',
      blindStructure: '盲注结构',
      blindLevel: '级别',
      blindSmallBig: '小盲 / 大盲',
      blindAnte: '前注',
      resultLabel: '成绩',
      liveLabel: '直播',
      resultPending: '成绩数据待公布',
      livePending: '直播数据待公布',
      backToSchedule: '返回赛程',
      backToRanking: '返回排名',
      backToNews: '返回新闻',
      backToAbout: '返回介绍',
      backHome: '返回首页 ↗',
      backToScheduleArrow: '返回赛程 ↗',
      playerProfile: '选手资料',
      rankLabel: '排名',
      countryLabel: '国家/地区',
      earningsLabel: '奖金',
      bioPending: '选手资料详情将在管理后台中维护。',
      resultHistory: '成绩 / 参赛记录',
      noNews: '暂无已发布的新闻',
      newsNotes: '新闻 · 专栏 · 人物',
      exploreSchedule: '查看赛程',
      theSeries: '系列赛',
      theVenue: '比赛场馆',
      seriesDetail: '01 / 系列赛 · 详情',
      venueLabel: '场馆',
      dateLabel: '日期',
      guaranteedLabel: '保底',
      contentPending: '内容待更新',
      eventList: '赛事列表',
      schedulePending: '赛事赛程待公布',
      seriesWord: '系列赛',
      dateRangeLabel: '日期范围',
      eventsWord: '赛事',
      tba: '待定',
      scheduleKicker: '01 / 赛程 · 系列赛',
    },
  },
}

export type DetailSection = 'schedule' | 'event' | 'ranking' | 'news' | 'about'

export interface DetailLocaleContent {
  kicker: string
  title: string
  intro: string
}

/** Per-language hero copy for standalone detail pages. Items stay in English (official proper nouns). */
export const detailCopy: Record<Language, Record<DetailSection, DetailLocaleContent>> = {
  EN: {
    schedule: { kicker: '01 / SCHEDULE', title: 'SCHEDULE', intro: 'A considered calendar of live poker, from opening tables to championship nights.' },
    event: { kicker: 'EVENT / THE PROGRAM', title: 'THE TABLE IS SET', intro: 'Every event is built around momentum, precision, and the players who shape the room.' },
    ranking: { kicker: '03 / PLAYER RANKING', title: 'TOP PLAYERS', intro: 'The season belongs to the players who make every decision count.' },
    news: { kicker: '04 / FROM THE SERIES', title: 'INSIDE THE STORY.', intro: 'Reports, portraits, and moments from the Korea Series of Poker.' },
    about: { kicker: '01 / THE SERIES', title: 'MORE THAN A TOURNAMENT.', intro: "KSOP is a meeting place for Korea's sharpest minds, boldest plays, and most unforgettable stories." },
  },
  KR: {
    schedule: { kicker: '01 / 일정', title: '일정', intro: '오프닝 테이블부터 챔피언십의 밤까지, 신중하게 구성된 라이브 포커 캘린더.' },
    event: { kicker: '이벤트 / 프로그램', title: '테이블이 준비되었습니다', intro: '모든 이벤트는 흐름과 정밀함, 그리고 현장을 만들어가는 플레이어를 중심으로 설계됩니다.' },
    ranking: { kicker: '03 / 선수 랭킹', title: '탑 플레이어', intro: '매 결정이 중요한 선수들이 이번 시즌의 주인공입니다.' },
    news: { kicker: '04 / 시리즈 소식', title: '시리즈의 이야기.', intro: '코리아 시리즈 오브 포커의 현장 리포트, 인물, 순간들.' },
    about: { kicker: '01 / 시리즈', title: '토너먼트를 넘어서.', intro: 'KSOP는 한국 최고의 지성, 대담한 플레이, 잊을 수 없는 스토리가 만나는 곳입니다.' },
  },
  JP: {
    schedule: { kicker: '01 / スケジュール', title: 'スケジュール', intro: 'オープニングテーブルからチャンピオンシップナイトまで、練り上げられたライブポーカーカレンダー。' },
    event: { kicker: 'イベント / プログラム', title: 'テーブルは整った', intro: 'すべてのイベントは、勢いと精密さ、そして場を形作るプレイヤーを中心に設計されています。' },
    ranking: { kicker: '03 / プレイヤーランキング', title: 'トッププレイヤー', intro: '一つひとつの判断を大切にする選手たちが、このシーズンの主役です。' },
    news: { kicker: '04 / シリーズより', title: 'シリーズの物語。', intro: 'コリアシリーズオブポーカーの現場レポート、人物、瞬間。' },
    about: { kicker: '01 / シリーズ', title: 'トーナメントを超えて。', intro: 'KSOPは、韓国の鋭い頭脳、大胆なプレイ、忘れられない物語が出会う場所です。' },
  },
  CN: {
    schedule: { kicker: '01 / 赛程', title: '赛程', intro: '从开幕桌到冠军之夜，经过精心编排的现场扑克赛历。' },
    event: { kicker: '赛事 / 赛制', title: '牌桌已经摆好', intro: '每一场赛事都围绕节奏、精准以及塑造赛场的选手而打造。' },
    ranking: { kicker: '03 / 选手排名', title: '顶尖选手', intro: '属于那些让每个决定都有分量的选手的赛季。' },
    news: { kicker: '04 / 系列动态', title: '系列故事。', intro: '韩国扑克系列赛的报道、人物与瞬间。' },
    about: { kicker: '01 / 系列赛', title: '超越锦标赛。', intro: 'KSOP是韩国最睿智的头脑、最大胆的打法和最难忘的故事的交汇之地。' },
  },
}
