import type { EventItem, Language, NewsItem, PlayerItem, SiteContent } from './types'

const eventNames = [
  'NLH Poker Players Championship / Day 1A',
  'NLH Warm-up',
  'NLH Good Game 500',
  'PLO Kick-off',
  'NLH Deepstack',
  'PLO Night',
  'NLH Bigstack Hyper',
  'Satellite to #25 NLH Good Game 1000',
  'Main Event Day 1',
  'High Roller Championship',
]

const eventTypes = ['NLH', 'NLH', 'NLH', 'PLO', 'NLH', 'PLO', 'NLH', 'SATELLITE', 'MAIN EVENT', 'HIGH ROLLER'] as const

export function createSeedEvents(): EventItem[] {
  return Array.from({ length: 100 }, (_, index) => {
    const day = Math.min(22, 17 + Math.floor(index / 17))
    const name = eventNames[index % eventNames.length]
    const type = eventTypes[index % eventTypes.length]

    return {
      id: `event-${index + 1}`,
      date: `NOV ${day}`,
      dayLabel: `DAY ${index + 1}`,
      name: `${name} #${index + 1}`,
      type,
      buyInType: 'INVITATION',
      buyIn: ['₩8,000', '₩10,000', '₩12,000', '₩25,000', '₩50,000'][index % 5],
      gtd: ['₩8,000', '₩10,000', '₩12,000', '₩25,000', '₩50,000'][index % 5],
      startingChips: 15000,
      lateReg: 'LEVEL 8',
      levelTime: '15 MIN',
      blindStructure: [
        { level: 1, small: 100, big: 200, ante: 200 },
        { level: 2, small: 200, big: 400, ante: 400 },
      ],
      published: true,
      posterUrl: '',
      bannerUrl: '',
      thumbnailUrl: '',
    }
  })
}

import { generateSyntheticPlayers } from './synthetic-players'

export const seedPlayers: PlayerItem[] = generateSyntheticPlayers()

export const seedNews: NewsItem[] = [
  {
    slug: 'how-a-final-table-finds-its-rhythm',
    category: 'FIELD NOTES',
    date: '12.09.25',
    title: 'How a final table finds its rhythm',
    excerpt: 'Inside the tempo shifts that define a championship final table.',
    body: 'The final table rarely announces itself with fireworks. Instead, it settles into a rhythm — a sequence of small decisions that compound into a defining arc for the entire series.',
    published: true,
  },
  {
    slug: 'jun-hyuk-lee-playing-the-long-game',
    category: 'PLAYER PORTRAIT',
    date: '08.09.25',
    title: 'JUN-HYUK LEE: PLAYING THE LONG GAME',
    excerpt: 'A portrait of the current KSOP ranking leader.',
    body: 'JUN-HYUK LEE built his ranking through consistency rather than spectacle — patient lines, selective aggression, and a reputation for reading pressure points late in tournaments.',
    published: true,
  },
  {
    slug: 'seoul-after-dark-the-city-around-the-felt',
    category: 'KSOP JOURNAL',
    date: '01.09.25',
    title: 'Seoul, after dark: the city around the felt',
    excerpt: 'The city outside the arena becomes part of the KSOP experience.',
    body: 'When the cards pause, Seoul keeps moving. From Grand Hyatt to the late-night streets, the city offers its own rhythm to players between sessions.',
    published: true,
  },
]

export const seedContent: SiteContent = {
  heroImage: '/images/ksop-hero-arena.png',
  logoBlack: '/images/ksop-light-approved.png',
  logoWhite: '/images/ksop-dark-approved.png',
  seriesDate: '17 NOV 2026',
  seriesVenue: 'SEOUL · GRAND HYATT',
  seriesGtd: '₩1,500,000,000 GTD',
  countdownDays: 75,
  introTitle: 'More than\na tournament.',
  introBody: "KSOP is a meeting place for Korea's sharpest minds, boldest plays, and most unforgettable stories.",
  imageBreakLabel: 'THE TABLE IS SET',
  imageBreakTitle: 'See you',
  imageBreakEmphasis: 'at the felt.',
  copy: {
    EN: {
      ticker: '[LIVE NEXT EVENT] SEOUL GRAND PRIX · COUNTDOWN: 75D : 00H : 00M : 00S',
      nav: ['SCHEDULE', 'EVENT', 'RANKING', 'NEWS', 'ABOUT'],
      eyebrow: 'THE KOREA SERIES OF POKER · 2026',
      hero: 'THE PINNACLE OF LIVE POKER',
      intro: 'Where discipline meets instinct. A new standard for live poker in Korea.',
      register: 'REGISTER NOW',
      explore: 'EXPLORE EVENTS',
      guaranteed: 'GUARANTEED PRIZE POOL',
      invitation: 'INVITATION',
      stack: 'STARTING STACK',
      reg: 'REGISTRATION',
      schedule: 'EVENTS',
      ranking: 'TOP PLAYERS',
      news: 'INSIDE THE STORY.',
      follow: 'FOLLOW THE SERIES',
      buyin: 'BUY-IN',
      seatReserved: 'SEAT RESERVED',
      viewEvent: 'View event',
      viewEvents: 'View events',
      viewAllEvents: 'View all events',
      fullRanking: 'Full ranking',
      viewProfile: 'View profile',
      allNews: 'All news',
      readStory: 'Read the story',
      registerShort: 'Register',
      searchPlayer: 'Search player',
      showing: 'SHOWING {shown} OF {total} EVENTS',
      noEvents: 'NO EVENTS MATCH THE SELECTED FILTERS',
      clearFilters: 'CLEAR FILTERS',
      showMore: 'SHOW MORE ({remaining} REMAINING)',
      allDates: 'ALL DATES',
      openEvent: 'Open event page',
      seriesLabel: '01 / THE SERIES',
      scheduleLabel: '02 / UPCOMING SERIES',
      rankingLabel: '03 / PLAYER RANKING',
      newsLabel: '04 / FROM THE SERIES',
      introTitle: 'More than',
      introEmphasis: 'a tournament.',
      footerLine1: "Korea's premier live poker series.",
      footerLine2: 'Designed for the game.',
      countdown: 'COUNTDOWN',
      posterMonth: 'NOVEMBER',
      factChips: 'STARTING CHIPS',
      factLate: 'LATE REG.',
      factLevel: 'LEVEL TIME',
      factType: 'TYPE',
      factBuyin: 'BUY-IN',
      eventDetail: 'EVENT DETAIL',
      eventStatus: 'EVENT STATUS',
      regStatus: 'REGISTRATION STATUS',
      statusPending: 'STATUS PENDING',
      regPending: 'REGISTRATION PENDING',
      blindStructure: 'BLIND STRUCTURE',
      blindLevel: 'LEVEL',
      blindSmallBig: 'SMALL / BIG',
      blindAnte: 'ANTE',
      resultLabel: 'RESULT',
      liveLabel: 'LIVE',
      resultPending: 'RESULT DATA PENDING',
      livePending: 'LIVE DATA PENDING',
      backToSchedule: 'Back to schedule',
      backToRanking: 'Back to ranking',
      backToNews: 'Back to news',
      backToAbout: 'Back to about',
      backHome: 'BACK TO HOME ↗',
      backToScheduleArrow: 'BACK TO SCHEDULE ↗',
      playerProfile: 'PLAYER PROFILE',
      rankLabel: 'RANK',
      countryLabel: 'COUNTRY',
      earningsLabel: 'EARNINGS',
      bioPending: 'Player profile details will be managed from the admin panel.',
      resultHistory: 'RESULT / TOURNAMENT HISTORY',
      noNews: 'NO PUBLISHED NEWS',
      newsNotes: 'NEWS · NOTES · PORTRAITS',
      exploreSchedule: 'Explore the schedule',
      theSeries: 'THE SERIES',
      theVenue: 'THE VENUE',
      seriesDetail: '01 / THE SERIES · DETAIL',
      venueLabel: 'VENUE',
      dateLabel: 'DATE',
      guaranteedLabel: 'GUARANTEED',
      contentPending: 'CONTENT PENDING',
      eventList: 'EVENT LIST',
      schedulePending: 'EVENT SCHEDULE PENDING',
      seriesWord: 'SERIES',
      dateRangeLabel: 'DATE RANGE',
      eventsWord: 'EVENTS',
      tba: 'TBA',
      scheduleKicker: '01 / SCHEDULE · SERIES',
      about: {
        companyLabel: '01 / ABOUT KSOP',
        companyHeadline: 'Poker as culture and industry.',
        companyBody: [
          'Beyond running poker tournaments, KSOP is building a poker entertainment ecosystem where players, fans, partners, venues, and media connect.',
          'Tournament operations, player rankings, live content, media production, brand collaboration, and regional and corporate partnerships — connected on one platform.',
        ],
        historyLabel: '02 / HISTORY',
        milestones: [
          { label: 'BEGINNING', title: 'The start', description: 'Began as a project to run poker tournaments in a more systematic and trustworthy way.' },
          { label: 'BUILD', title: 'Build', description: 'Step-by-step construction of tournament operations, player data, live timers, and ranking structures.' },
          { label: 'EXPANSION', title: 'Expansion', description: 'Expanded into a poker entertainment structure connected with FLOPIN, PLAYPLACE, KSOP STUDIO, and PLAYSOFT.' },
          { label: 'NOW', title: 'Now', description: 'Connecting live tournaments, digital platforms, content production, and partner business in one system.' },
          { label: 'NEXT', title: 'Next', description: 'Expanding beyond Korea into Asian poker events, media, and player ecosystems.' },
        ],
        whatWeDoLabel: '03 / WHAT WE DO',
        whatWeDoGroups: [
          { title: 'TOURNAMENT', items: ['KSOP Series', 'Event operations', 'Player experience'] },
          { title: 'RANKING & DATA', items: ['KSOP Ranking', 'Player profiles', 'Results archive'] },
          { title: 'MEDIA & CONTENT', items: ['Live content', 'Short-form', 'Poster / editorial', 'Interview', 'YouTube / FLOPIN distribution'] },
          { title: 'PARTNERSHIP', items: ['Corporate promotion', 'Sponsorship', 'Venue partnership', 'MICE collaboration'] },
        ],
        visionLabel: '04 / VISION',
        visionHeadline: 'From running tournaments to building a poker ecosystem.',
        visionBody: 'KSOP pursues a sustainable poker industry where player records endure, fans consume content, partners build brand value, and regions and venues grow together — not one-off events.',
        visionBullets: [
          'Fair and transparent tournament operations',
          'Advanced player ranking and records',
          'FLOPIN-based digital experiences',
          'Global series and international exchange',
          'Brand, media, and regional partnerships',
          'Content IP and broadcast production',
        ],
        workLabel: '05 / WORK WITH KSOP',
        workHeadline: 'Build with KSOP',
        cooperations: [
          { title: 'MICE', description: 'Collaboration on KSOP tournaments, regional events, conventions, tourism, and complex events.', cta: 'Apply for MICE' },
          { title: 'Corporate promotion', description: 'Corporate promotion through KSOP events, website, content, and on-site branding.', cta: 'Inquire' },
          { title: 'Media', description: 'Media registration and collaboration for coverage, filming, interviews, and broadcasts.', cta: 'Apply as media' },
          { title: 'Sponsorship / Partnership', description: 'Collaboration for companies and brands creating experiences with KSOP.', cta: 'Partner with us' },
        ],
        partnersLabel: '06 / PARTNERS',
        partnersHeadline: 'Partners with KSOP',
        partnersPending: 'Partners to be announced',
        contactLabel: '07 / CONTACT',
        contactHeadline: 'Start the conversation.',
        contactBody: 'Tournaments, promotion, media, partnerships — reach out about any collaboration.',
        contactCta: 'Contact us',
        seriesLinkNote: 'Looking for the series or the venue?',
        forms: {
          mice: {
            title: 'MICE application',
            description: 'Collaboration on KSOP tournaments, regional events, conventions, tourism, and complex events.',
            cta: 'Apply for MICE',
            pending: 'Application intake is being prepared.',
            fields: [
              { label: 'Company / Organization' },
              { label: 'Contact name' },
              { label: 'Email' },
              { label: 'Phone' },
              { label: 'Event region' },
              { label: 'Event type', options: ['Poker tournament', 'Regional event', 'Convention', 'Tourism', 'Complex event', 'Other'] },
              { label: 'Expected dates' },
              { label: 'Expected scale', options: ['Under 50', '50–150', '150–300', 'Over 300'] },
              { label: 'Details' },
            ],
          },
          corporate: {
            title: 'Corporate promotion',
            description: 'Corporate promotion through KSOP events, website, content, and on-site branding.',
            cta: 'Inquire',
            pending: 'Application intake is being prepared.',
            fields: [
              { label: 'Company' },
              { label: 'Brand' },
              { label: 'Contact name' },
              { label: 'Email' },
              { label: 'Phone' },
              { label: 'Promotion goal' },
              { label: 'Desired channels', options: ['On-site', 'Website', 'Live content', 'Social / short-form', 'Combined'] },
              { label: 'Campaign period' },
              { label: 'Budget range (optional)', options: ['Under ₩5M', '₩5–20M', '₩20–50M', 'Over ₩50M', 'To discuss'] },
              { label: 'Details' },
            ],
          },
          media: {
            title: 'Media application',
            description: 'Media registration and collaboration for coverage, filming, interviews, and broadcasts.',
            cta: 'Apply as media',
            pending: 'Application intake is being prepared.',
            fields: [
              { label: 'Media / Company' },
              { label: 'Contact name' },
              { label: 'Email' },
              { label: 'Phone' },
              { label: 'Media type', options: ['Press', 'Broadcast', 'YouTube / Creator', 'Photo', 'Other'] },
              { label: 'Coverage purpose' },
              { label: 'Filming', options: ['Yes', 'No', 'Undecided'] },
              { label: 'Target event' },
              { label: 'Request details' },
            ],
          },
          sponsor: {
            title: 'Sponsorship / Partnership',
            description: 'Collaboration for companies and brands creating experiences with KSOP.',
            cta: 'Partner with us',
            pending: 'Application intake is being prepared.',
            fields: [
              { label: 'Company' },
              { label: 'Brand' },
              { label: 'Contact' },
              { label: 'Email' },
              { label: 'Phone' },
              { label: 'Sponsorship type', options: ['Cash', 'Product', 'Service', 'Combined'] },
              { label: 'Cash / product / service' },
              { label: 'Target event' },
              { label: 'Proposal' },
            ],
          },
        },
      },
    },
    KR: {
      ticker: '[LIVE NEXT EVENT] 서울 그랑프리 · 카운트다운: 14일 : 08시간 : 42분 : 12초',
      nav: ['일정', '이벤트', '랭킹', '뉴스', '소개'],
      eyebrow: '코리아 시리즈 오브 포커 · 2026',
      hero: '라이브 포커의 정점',
      intro: '절제와 본능이 만나는 곳. 한국 라이브 포커의 새로운 기준.',
      register: '지금 등록하기',
      explore: '이벤트 보기',
      guaranteed: '보장 상금',
      invitation: 'INVITATION',
      stack: '스타팅 스택',
      reg: '등록 마감',
      schedule: '주요 이벤트',
      ranking: '탑플레이어',
      news: '시리즈의 이야기.',
      follow: '시리즈 팔로우',
      buyin: '바이인',
      seatReserved: '좌석 예약됨',
      viewEvent: '이벤트 보기',
      viewEvents: '이벤트 보기',
      viewAllEvents: '모든 이벤트 보기',
      fullRanking: '전체 랭킹 보기',
      viewProfile: '프로필 보기',
      allNews: '모든 뉴스',
      readStory: '이야기 읽기',
      registerShort: '등록',
      searchPlayer: '선수 검색',
      showing: '전체 {total}개 중 {shown}개 표시',
      noEvents: '조건에 맞는 이벤트가 없습니다',
      clearFilters: '필터 초기화',
      showMore: '더 보기 ({remaining}개 남음)',
      allDates: '전체 날짜',
      openEvent: '이벤트 페이지 열기',
      seriesLabel: '01 / 시리즈',
      scheduleLabel: '02 / 예정된 시리즈',
      rankingLabel: '03 / 선수 랭킹',
      newsLabel: '04 / 시리즈 소식',
      introTitle: '토너먼트를',
      introEmphasis: '넘어서.',
      footerLine1: '한국 최고의 라이브 포커 시리즈.',
      footerLine2: '게임을 위해 디자인되었습니다.',
      countdown: '카운트다운',
      posterMonth: '11월',
      factChips: '스타팅 칩',
      factLate: '레이트 레지',
      factLevel: '레벨 시간',
      factType: '타입',
      factBuyin: '바이인',
      eventDetail: '이벤트 상세',
      eventStatus: '이벤트 상태',
      regStatus: '등록 상태',
      statusPending: '상태 업데이트 예정',
      regPending: '등록 오픈 예정',
      blindStructure: '블라인드 구조',
      blindLevel: '레벨',
      blindSmallBig: '스몰 / 빅',
      blindAnte: '앤티',
      resultLabel: '결과',
      liveLabel: '라이브',
      resultPending: '결과 데이터 업데이트 예정',
      livePending: '라이브 데이터 업데이트 예정',
      backToSchedule: '일정으로 돌아가기',
      backToRanking: '랭킹으로 돌아가기',
      backToNews: '뉴스로 돌아가기',
      backToAbout: '소개로 돌아가기',
      backHome: '홈으로 돌아가기 ↗',
      backToScheduleArrow: '일정으로 돌아가기 ↗',
      playerProfile: '선수 프로필',
      rankLabel: '순위',
      countryLabel: '국가',
      earningsLabel: '상금',
      bioPending: '선수 프로필 상세 정보는 관리자 패널에서 관리됩니다.',
      resultHistory: '결과 / 토너먼트 기록',
      noNews: '공개된 뉴스가 없습니다',
      newsNotes: '뉴스 · 노트 · 포트레이트',
      exploreSchedule: '일정 살펴보기',
      theSeries: '시리즈',
      theVenue: '장소',
      seriesDetail: '01 / 시리즈 · 상세',
      venueLabel: '장소',
      dateLabel: '날짜',
      guaranteedLabel: '개런티',
      contentPending: '콘텐츠 업데이트 예정',
      eventList: '이벤트 목록',
      schedulePending: '이벤트 일정 업데이트 예정',
      seriesWord: '시리즈',
      dateRangeLabel: '기간',
      eventsWord: '이벤트',
      tba: '미정',
      scheduleKicker: '01 / 일정 · 시리즈',
      about: {
        companyLabel: '01 / ABOUT KSOP',
        companyHeadline: '포커를 하나의 문화와 산업으로.',
        companyBody: [
          'KSOP는 단순한 포커 대회 운영을 넘어, 선수·팬·파트너·매장·미디어가 함께 연결되는 포커 엔터테인먼트 생태계를 만드는 것을 목표로 한다.',
          '대회 운영, 선수 랭킹, 라이브 콘텐츠, 미디어 제작, 브랜드 협업, 지역 및 기업 파트너십을 하나의 플랫폼으로 연결한다.',
        ],
        historyLabel: '02 / HISTORY',
        milestones: [
          { label: 'BEGINNING', title: '시작', description: '포커 대회를 더 체계적이고 신뢰도 높은 방식으로 운영하기 위한 프로젝트에서 시작.' },
          { label: 'BUILD', title: '구축', description: '대회 운영 시스템, 선수 데이터, 라이브 타이머, 랭킹 구조를 단계적으로 구축.' },
          { label: 'EXPANSION', title: '확장', description: 'FLOPIN, PLAYPLACE, KSOP STUDIO, PLAYSOFT와 연결되는 포커 엔터테인먼트 구조로 확장.' },
          { label: 'NOW', title: '현재', description: '오프라인 대회와 디지털 플랫폼, 콘텐츠 제작, 파트너 비즈니스를 하나의 체계로 연결하는 단계.' },
          { label: 'NEXT', title: '다음', description: '국내를 넘어 아시아권 포커 이벤트·미디어·선수 생태계로 확장.' },
        ],
        whatWeDoLabel: '03 / WHAT WE DO',
        whatWeDoGroups: [
          { title: 'TOURNAMENT', items: ['KSOP Series', 'Event operations', 'Player experience'] },
          { title: 'RANKING & DATA', items: ['KSOP Ranking', 'Player profiles', 'Results archive'] },
          { title: 'MEDIA & CONTENT', items: ['Live content', 'Short-form', 'Poster / editorial', 'Interview', 'YouTube / FLOPIN distribution'] },
          { title: 'PARTNERSHIP', items: ['Corporate promotion', 'Sponsorship', 'Venue partnership', 'MICE collaboration'] },
        ],
        visionLabel: '04 / VISION',
        visionHeadline: '대회를 만드는 회사에서, 포커 생태계를 만드는 회사로.',
        visionBody: 'KSOP는 단발성 이벤트가 아니라 선수의 기록이 남고, 팬이 콘텐츠를 소비하며, 파트너가 브랜드 가치를 만들고, 지역과 매장이 함께 성장할 수 있는 지속 가능한 포커 산업 구조를 지향한다.',
        visionBullets: [
          '공정하고 투명한 대회 운영',
          '선수 랭킹 및 기록 체계 고도화',
          'FLOPIN 기반 디지털 경험 확장',
          '글로벌 시리즈 및 해외 선수 교류',
          '브랜드·미디어·지역 파트너십 확대',
          '콘텐츠 IP 및 방송 제작 강화',
        ],
        workLabel: '05 / WORK WITH KSOP',
        workHeadline: 'KSOP와 함께 만들기',
        cooperations: [
          { title: 'MICE 신청', description: 'KSOP 대회, 지역 행사, 컨벤션, 관광 및 복합 이벤트 협업 문의.', cta: 'MICE 협업 신청' },
          { title: '기업홍보 신청', description: 'KSOP 이벤트, 홈페이지, 콘텐츠, 현장 브랜딩을 활용한 기업 홍보 협업.', cta: '기업홍보 문의' },
          { title: '미디어 신청', description: '취재, 촬영, 인터뷰, 방송, 콘텐츠 제작 관련 미디어 등록 및 협업 신청.', cta: '미디어 신청' },
          { title: '협찬 / 파트너십', description: 'KSOP와 함께 브랜드 경험을 만들 기업·브랜드·파트너를 위한 협업 문의.', cta: '파트너십 문의' },
        ],
        partnersLabel: '06 / PARTNERS',
        partnersHeadline: 'KSOP와 함께하는 파트너',
        partnersPending: '파트너 공개 준비 중',
        contactLabel: '07 / CONTACT',
        contactHeadline: '이야기를 시작해 보세요.',
        contactBody: '대회, 홍보, 미디어, 파트너십 — 어떤 협업이든 먼저 편하게 문의해 주세요.',
        contactCta: '협업 문의하기',
        seriesLinkNote: '시리즈와 장소가 궁금하다면',
        forms: {
          mice: {
            title: 'MICE 신청',
            description: 'KSOP 대회, 지역 행사, 컨벤션, 관광 및 복합 이벤트 협업 문의.',
            cta: 'MICE 협업 신청',
            pending: '신청 접수가 준비 중입니다.',
            fields: [
              { label: '회사/기관명' },
              { label: '담당자명' },
              { label: '이메일' },
              { label: '연락처' },
              { label: '행사 지역' },
              { label: '행사 유형', options: ['포커 대회', '지역 행사', '컨벤션', '관광 연계', '복합 이벤트', '기타'] },
              { label: '예상 일정' },
              { label: '예상 규모', options: ['50명 미만', '50–150명', '150–300명', '300명 이상'] },
              { label: '문의 내용' },
            ],
          },
          corporate: {
            title: '기업홍보 신청',
            description: 'KSOP 이벤트, 홈페이지, 콘텐츠, 현장 브랜딩을 활용한 기업 홍보 협업.',
            cta: '기업홍보 문의',
            pending: '신청 접수가 준비 중입니다.',
            fields: [
              { label: '회사명' },
              { label: '브랜드명' },
              { label: '담당자명' },
              { label: '이메일' },
              { label: '연락처' },
              { label: '홍보 목적' },
              { label: '희망 노출 채널', options: ['이벤트 현장', '홈페이지', '라이브 콘텐츠', 'SNS/숏폼', '복합 노출'] },
              { label: '캠페인 기간' },
              { label: '예산 범위 (선택)', options: ['500만원 미만', '500만–2,000만원', '2,000만–5,000만원', '5,000만원 이상', '협의'] },
              { label: '문의 내용' },
            ],
          },
          media: {
            title: '미디어 신청',
            description: '취재, 촬영, 인터뷰, 방송, 콘텐츠 제작 관련 미디어 등록 및 협업 신청.',
            cta: '미디어 신청',
            pending: '신청 접수가 준비 중입니다.',
            fields: [
              { label: '미디어/회사명' },
              { label: '담당자명' },
              { label: '이메일' },
              { label: '연락처' },
              { label: '미디어 유형', options: ['언론/보도', '방송', '유튜브/크리에이터', '사진', '기타'] },
              { label: '취재 목적' },
              { label: '촬영 여부', options: ['촬영 함', '촬영 안 함', '미정'] },
              { label: '희망 이벤트' },
              { label: '요청 내용' },
            ],
          },
          sponsor: {
            title: '협찬 / 파트너십',
            description: 'KSOP와 함께 브랜드 경험을 만들 기업·브랜드·파트너를 위한 협업 문의.',
            cta: '파트너십 문의',
            pending: '신청 접수가 준비 중입니다.',
            fields: [
              { label: '회사명' },
              { label: '브랜드명' },
              { label: '담당자' },
              { label: '이메일' },
              { label: '연락처' },
              { label: '협찬 유형', options: ['현금 협찬', '제품 협찬', '서비스 협찬', '복합 협찬'] },
              { label: '현금/제품/서비스 구분' },
              { label: '희망 이벤트' },
              { label: '제안 내용' },
            ],
          },
        },
      },
    },
    JP: {
      ticker: '[LIVE NEXT EVENT] ソウル・グランプリ · カウントダウン: 14日 : 08時間 : 42分 : 12秒',
      nav: ['スケジュール', 'イベント', 'ランキング', 'ニュース', '紹介'],
      eyebrow: 'コリアシリーズオブポーカー · 2026',
      hero: 'ライブポーカーの頂点',
      intro: '規律と本能が出会う場所。韓国ライブポーカーの新基準。',
      register: '今すぐ登録',
      explore: 'イベントを見る',
      guaranteed: '保証賞金',
      invitation: 'INVITATION',
      buyin: 'バイイン',
      stack: 'スターティングスタック',
      reg: '登録期間',
      schedule: '主要イベント',
      ranking: 'トッププレイヤー',
      news: 'シリーズの物語。',
      follow: 'シリーズをフォロー',
      seatReserved: '予約済み',
      viewEvent: 'イベントを見る',
      viewEvents: 'イベントを見る',
      viewAllEvents: 'すべてのイベントを見る',
      fullRanking: '全ランキングを見る',
      viewProfile: 'プロフィールを見る',
      allNews: 'すべてのニュース',
      readStory: '記事を読む',
      registerShort: '登録',
      searchPlayer: '選手を検索',
      showing: '{total}件中{shown}件を表示',
      noEvents: '条件に合うイベントがありません',
      clearFilters: 'フィルターをクリア',
      showMore: 'さらに表示（残り{remaining}件）',
      allDates: 'すべての日程',
      openEvent: 'イベントページを開く',
      seriesLabel: '01 / シリーズ',
      scheduleLabel: '02 / 開催予定シリーズ',
      rankingLabel: '03 / プレイヤーランキング',
      newsLabel: '04 / シリーズより',
      introTitle: 'トーナメントを',
      introEmphasis: '超えて。',
      footerLine1: '韓国最高峰のライブポーカーシリーズ。',
      footerLine2: 'ゲームのためにデザインされました。',
      countdown: 'カウントダウン',
      posterMonth: '11月',
      factChips: 'スターティングチップ',
      factLate: 'レイトレジ',
      factLevel: 'レベル時間',
      factType: 'タイプ',
      factBuyin: 'バイイン',
      eventDetail: 'イベント詳細',
      eventStatus: 'イベントステータス',
      regStatus: '登録ステータス',
      statusPending: 'ステータス未定',
      regPending: '登録受付前',
      blindStructure: 'ブラインドストラクチャー',
      blindLevel: 'レベル',
      blindSmallBig: 'スモール / ビッグ',
      blindAnte: 'アンティ',
      resultLabel: 'リザルト',
      liveLabel: 'ライブ',
      resultPending: 'リザルトは後日公開',
      livePending: 'ライブ配信は後日公開',
      backToSchedule: 'スケジュールに戻る',
      backToRanking: 'ランキングに戻る',
      backToNews: 'ニュースに戻る',
      backToAbout: '紹介に戻る',
      backHome: 'ホームに戻る ↗',
      backToScheduleArrow: 'スケジュールに戻る ↗',
      playerProfile: '選手プロフィール',
      rankLabel: 'ランク',
      countryLabel: '国籍',
      earningsLabel: '獲得賞金',
      bioPending: '選手プロフィールの詳細は管理パネルで管理されます。',
      resultHistory: 'リザルト / トーナメント履歴',
      noNews: '公開中のニュースがありません',
      newsNotes: 'ニュース · ノート · ポートレート',
      exploreSchedule: 'スケジュールを見る',
      theSeries: 'シリーズ',
      theVenue: '会場',
      seriesDetail: '01 / シリーズ · 詳細',
      venueLabel: '会場',
      dateLabel: '日程',
      guaranteedLabel: 'ギャランティ',
      contentPending: 'コンテンツ準備中',
      eventList: 'イベントリスト',
      schedulePending: 'イベントスケジュールは後日公開',
      seriesWord: 'シリーズ',
      dateRangeLabel: '開催期間',
      eventsWord: 'イベント',
      tba: '未定',
      scheduleKicker: '01 / スケジュール · シリーズ',
      about: {
        companyLabel: '01 / ABOUT KSOP',
        companyHeadline: 'ポーカーを文化と産業に。',
        companyBody: [
          'KSOPはポーカートーナメントの運営を超え、選手・ファン・パートナー・店舗・メディアがつながるポーカーエンターテインメントのエコシステムを目指す。',
          '大会運営、選手ランキング、ライブコンテンツ、メディア制作、ブランド協業、地域・企業パートナーシップを一つのプラットフォームでつなぐ。',
        ],
        historyLabel: '02 / HISTORY',
        milestones: [
          { label: 'BEGINNING', title: '始まり', description: 'ポーカー大会をより体系的で信頼性の高い方法で運営するプロジェクトから開始。' },
          { label: 'BUILD', title: '構築', description: '大会運営システム、選手データ、ライブタイマー、ランキング構造を段階的に構築。' },
          { label: 'EXPANSION', title: '拡張', description: 'FLOPIN、PLAYPLACE、KSOP STUDIO、PLAYSOFTとつながるポーカーエンターテインメント構造へ拡張。' },
          { label: 'NOW', title: '現在', description: 'オフライン大会とデジタルプラットフォーム、コンテンツ制作、パートナービジネスを一つの体系でつなぐ段階。' },
          { label: 'NEXT', title: '次へ', description: '国内を超え、アジアのポーカーイベント・メディア・選手エコシステムへ拡張。' },
        ],
        whatWeDoLabel: '03 / WHAT WE DO',
        whatWeDoGroups: [
          { title: 'TOURNAMENT', items: ['KSOP Series', 'Event operations', 'Player experience'] },
          { title: 'RANKING & DATA', items: ['KSOP Ranking', 'Player profiles', 'Results archive'] },
          { title: 'MEDIA & CONTENT', items: ['Live content', 'Short-form', 'Poster / editorial', 'Interview', 'YouTube / FLOPIN distribution'] },
          { title: 'PARTNERSHIP', items: ['Corporate promotion', 'Sponsorship', 'Venue partnership', 'MICE collaboration'] },
        ],
        visionLabel: '04 / VISION',
        visionHeadline: '大会を作る会社から、ポーカーの生態系を作る会社へ。',
        visionBody: 'KSOPは単発イベントではなく、選手の記録が残り、ファンがコンテンツを楽しみ、パートナーがブランド価値を生み、地域と店舗が共に成長できる持続可能なポーカー産業構造を目指す。',
        visionBullets: [
          '公正で透明な大会運営',
          '選手ランキングと記録体系の高度化',
          'FLOPIN基盤のデジタル体験拡張',
          'グローバルシリーズと海外選手交流',
          'ブランド・メディア・地域パートナーシップ拡大',
          'コンテンツIPと放送制作の強化',
        ],
        workLabel: '05 / WORK WITH KSOP',
        workHeadline: 'KSOPと共に作る',
        cooperations: [
          { title: 'MICE申請', description: 'KSOP大会、地域イベント、コンベンション、観光・複合イベントの協業相談。', cta: 'MICE協業を申請' },
          { title: '企業PR申請', description: 'KSOPイベント、サイト、コンテンツ、会場ブランディングを活用した企業PR協業。', cta: '企業PRの相談' },
          { title: 'メディア申請', description: '取材、撮影、インタビュー、放送、コンテンツ制作に関するメディア登録・協業申請。', cta: 'メディア申請' },
          { title: '協賛 / パートナーシップ', description: 'KSOPと共にブランド体験を作る企業・ブランド・パートナーのための協業相談。', cta: 'パートナーシップ相談' },
        ],
        partnersLabel: '06 / PARTNERS',
        partnersHeadline: 'KSOPと共にあるパートナー',
        partnersPending: 'パートナー公開準備中',
        contactLabel: '07 / CONTACT',
        contactHeadline: '話を始めましょう。',
        contactBody: '大会、PR、メディア、パートナーシップ — どんな協業もまず気軽にご相談ください。',
        contactCta: '協業を相談する',
        seriesLinkNote: 'シリーズや会場についてはこちら',
        forms: {
          mice: {
            title: 'MICE申請',
            description: 'KSOP大会、地域イベント、コンベンション、観光・複合イベントの協業相談。',
            cta: 'MICE協業を申請',
            pending: '申請受付を準備中です。',
            fields: [
              { label: '会社/機関名' },
              { label: '担当者名' },
              { label: 'メール' },
              { label: '連絡先' },
              { label: '開催地域' },
              { label: 'イベント種別', options: ['ポーカートーナメント', '地域イベント', 'コンベンション', '観光連携', '複合イベント', 'その他'] },
              { label: '想定日程' },
              { label: '想定規模', options: ['50名未満', '50–150名', '150–300名', '300名以上'] },
              { label: '相談内容' },
            ],
          },
          corporate: {
            title: '企業PR申請',
            description: 'KSOPイベント、サイト、コンテンツ、会場ブランディングを活用した企業PR協業。',
            cta: '企業PRの相談',
            pending: '申請受付を準備中です。',
            fields: [
              { label: '会社名' },
              { label: 'ブランド名' },
              { label: '担当者名' },
              { label: 'メール' },
              { label: '連絡先' },
              { label: 'PR目的' },
              { label: '希望露出チャネル', options: ['会場', 'サイト', 'ライブコンテンツ', 'SNS/ショート', '複合露出'] },
              { label: 'キャンペーン期間' },
              { label: '予算範囲 (任意)', options: ['500万ウォン未満', '500万–2,000万ウォン', '2,000万–5,000万ウォン', '5,000万ウォン以上', '相談'] },
              { label: '相談内容' },
            ],
          },
          media: {
            title: 'メディア申請',
            description: '取材、撮影、インタビュー、放送、コンテンツ制作に関するメディア登録・協業申請。',
            cta: 'メディア申請',
            pending: '申請受付を準備中です。',
            fields: [
              { label: 'メディア/会社名' },
              { label: '担当者名' },
              { label: 'メール' },
              { label: '連絡先' },
              { label: 'メディア種別', options: ['報道', '放送', 'YouTube/クリエイター', '写真', 'その他'] },
              { label: '取材目的' },
              { label: '撮影の有無', options: ['あり', 'なし', '未定'] },
              { label: '希望イベント' },
              { label: 'リクエスト内容' },
            ],
          },
          sponsor: {
            title: '協賛 / パートナーシップ',
            description: 'KSOPと共にブランド体験を作る企業・ブランド・パートナーのための協業相談。',
            cta: 'パートナーシップ相談',
            pending: '申請受付を準備中です。',
            fields: [
              { label: '会社名' },
              { label: 'ブランド名' },
              { label: '担当者' },
              { label: 'メール' },
              { label: '連絡先' },
              { label: '協賛種別', options: ['現金協賛', '製品協賛', 'サービス協賛', '複合協賛'] },
              { label: '現金/製品/サービス区分' },
              { label: '希望イベント' },
              { label: '提案内容' },
            ],
          },
        },
      },
    },
    CN: {
      ticker: '[LIVE NEXT EVENT] 首尔大奖赛 · 倒计时: 14天 : 08小时 : 42分 : 12秒',
      nav: ['赛程', '赛事', '排名', '新闻', '介绍'],
      eyebrow: '韩国扑克系列赛 · 2026',
      hero: '现场扑克的巅峰',
      intro: '纪律与本能相遇的地方。韩国现场扑克的新标准。',
      register: '立即报名',
      explore: '查看赛事',
      guaranteed: '保证奖金',
      invitation: 'INVITATION',
      buyin: '买入',
      stack: '起始筹码',
      reg: '报名截止',
      schedule: '主要赛事',
      ranking: '顶尖选手',
      news: '系列故事。',
      follow: '关注赛事',
      seatReserved: '已预留座位',
      viewEvent: '查看赛事',
      viewEvents: '查看赛事',
      viewAllEvents: '查看所有赛事',
      fullRanking: '查看完整排名',
      viewProfile: '查看选手资料',
      allNews: '所有新闻',
      readStory: '阅读报道',
      registerShort: '报名',
      searchPlayer: '搜索选手',
      showing: '共{total}场赛事，显示{shown}场',
      noEvents: '没有符合筛选条件的赛事',
      clearFilters: '清除筛选',
      showMore: '显示更多（还剩{remaining}场）',
      allDates: '所有日期',
      openEvent: '打开赛事页面',
      seriesLabel: '01 / 系列赛',
      scheduleLabel: '02 / 即将到来的系列赛',
      rankingLabel: '03 / 选手排名',
      newsLabel: '04 / 系列动态',
      introTitle: '超越',
      introEmphasis: '锦标赛。',
      footerLine1: '韩国顶级现场扑克系列赛。',
      footerLine2: '为比赛而设计。',
      countdown: '倒计时',
      posterMonth: '11月',
      factChips: '起始筹码',
      factLate: '延迟报名',
      factLevel: '级别时长',
      factType: '类型',
      factBuyin: '买入',
      eventDetail: '赛事详情',
      eventStatus: '赛事状态',
      regStatus: '报名状态',
      statusPending: '状态待定',
      regPending: '报名尚未开放',
      blindStructure: '盲注结构',
      blindLevel: '级别',
      blindSmallBig: '小盲 / 大盲',
      blindAnte: '前注',
      resultLabel: '成绩',
      liveLabel: '直播',
      resultPending: '成绩数据待公布',
      livePending: '直播数据待公布',
      backToSchedule: '返回赛程',
      backToRanking: '返回排名',
      backToNews: '返回新闻',
      backToAbout: '返回介绍',
      backHome: '返回首页 ↗',
      backToScheduleArrow: '返回赛程 ↗',
      playerProfile: '选手资料',
      rankLabel: '排名',
      countryLabel: '国家/地区',
      earningsLabel: '奖金',
      bioPending: '选手资料详情将在管理后台中维护。',
      resultHistory: '成绩 / 参赛记录',
      noNews: '暂无已发布的新闻',
      newsNotes: '新闻 · 专栏 · 人物',
      exploreSchedule: '查看赛程',
      theSeries: '系列赛',
      theVenue: '比赛场馆',
      seriesDetail: '01 / 系列赛 · 详情',
      venueLabel: '场馆',
      dateLabel: '日期',
      guaranteedLabel: '保底',
      contentPending: '内容待更新',
      eventList: '赛事列表',
      schedulePending: '赛事赛程待公布',
      seriesWord: '系列赛',
      dateRangeLabel: '日期范围',
      eventsWord: '赛事',
      tba: '待定',
      scheduleKicker: '01 / 赛程 · 系列赛',
      about: {
        companyLabel: '01 / ABOUT KSOP',
        companyHeadline: '让扑克成为一种文化与产业。',
        companyBody: [
          'KSOP不止于运营扑克赛事,目标是打造连接选手、粉丝、合作伙伴、场馆与媒体的扑克娱乐生态。',
          '赛事运营、选手排名、直播内容、媒体制作、品牌合作、地区与企业合作,在一个平台上连接。',
        ],
        historyLabel: '02 / HISTORY',
        milestones: [
          { label: 'BEGINNING', title: '起点', description: '始于以更系统、更可信的方式运营扑克赛事的项目。' },
          { label: 'BUILD', title: '搭建', description: '分阶段搭建赛事运营系统、选手数据、直播计时与排名结构。' },
          { label: 'EXPANSION', title: '扩展', description: '扩展为连接FLOPIN、PLAYPLACE、KSOP STUDIO与PLAYSOFT的扑克娱乐结构。' },
          { label: 'NOW', title: '现在', description: '正将线下赛事、数字平台、内容制作与合作业务连接为一个体系。' },
          { label: 'NEXT', title: '未来', description: '走向韩国之外,扩展至亚洲扑克赛事、媒体与选手生态。' },
        ],
        whatWeDoLabel: '03 / WHAT WE DO',
        whatWeDoGroups: [
          { title: 'TOURNAMENT', items: ['KSOP Series', 'Event operations', 'Player experience'] },
          { title: 'RANKING & DATA', items: ['KSOP Ranking', 'Player profiles', 'Results archive'] },
          { title: 'MEDIA & CONTENT', items: ['Live content', 'Short-form', 'Poster / editorial', 'Interview', 'YouTube / FLOPIN distribution'] },
          { title: 'PARTNERSHIP', items: ['Corporate promotion', 'Sponsorship', 'Venue partnership', 'MICE collaboration'] },
        ],
        visionLabel: '04 / VISION',
        visionHeadline: '从办赛的公司,到打造扑克生态的公司。',
        visionBody: 'KSOP追求的不是一次性赛事,而是选手留名、粉丝消费内容、合作伙伴创造品牌价值、地区与场馆共同成长的可持续扑克产业结构。',
        visionBullets: [
          '公平透明的赛事运营',
          '选手排名与纪录体系升级',
          '基于FLOPIN的数字体验扩展',
          '全球系列赛与海外选手交流',
          '品牌、媒体与地区合作扩大',
          '内容IP与转播制作加强',
        ],
        workLabel: '05 / WORK WITH KSOP',
        workHeadline: '与KSOP共创',
        cooperations: [
          { title: 'MICE申请', description: 'KSOP赛事、地区活动、会展、旅游及综合赛事合作咨询。', cta: '申请MICE合作' },
          { title: '企业宣传申请', description: '利用KSOP赛事、官网、内容与现场品牌展示的企业宣传合作。', cta: '企业宣传咨询' },
          { title: '媒体申请', description: '采访、拍摄、专访、转播与内容制作相关的媒体登记与合作申请。', cta: '媒体申请' },
          { title: '赞助 / 合作', description: '面向与KSOP共创品牌体验的企业、品牌与合作伙伴的合作咨询。', cta: '合作咨询' },
        ],
        partnersLabel: '06 / PARTNERS',
        partnersHeadline: '与KSOP同行的合作伙伴',
        partnersPending: '合作伙伴即将公布',
        contactLabel: '07 / CONTACT',
        contactHeadline: '开始对话吧。',
        contactBody: '赛事、宣传、媒体、合作——任何合作都欢迎先联系我们。',
        contactCta: '联系合作',
        seriesLinkNote: '想了解系列赛或场馆?',
        forms: {
          mice: {
            title: 'MICE申请',
            description: 'KSOP赛事、地区活动、会展、旅游及综合赛事合作咨询。',
            cta: '申请MICE合作',
            pending: '申请受理正在准备中。',
            fields: [
              { label: '公司/机构名称' },
              { label: '负责人姓名' },
              { label: '邮箱' },
              { label: '联系电话' },
              { label: '活动地区' },
              { label: '活动类型', options: ['扑克赛事', '地区活动', '会展', '旅游联动', '综合赛事', '其他'] },
              { label: '预计时间' },
              { label: '预计规模', options: ['50人以下', '50–150人', '150–300人', '300人以上'] },
              { label: '咨询内容' },
            ],
          },
          corporate: {
            title: '企业宣传申请',
            description: '利用KSOP赛事、官网、内容与现场品牌展示的企业宣传合作。',
            cta: '企业宣传咨询',
            pending: '申请受理正在准备中。',
            fields: [
              { label: '公司名称' },
              { label: '品牌名称' },
              { label: '负责人姓名' },
              { label: '邮箱' },
              { label: '联系电话' },
              { label: '宣传目的' },
              { label: '期望曝光渠道', options: ['赛事现场', '官网', '直播内容', '社交/短视频', '组合曝光'] },
              { label: '推广周期' },
              { label: '预算范围 (选填)', options: ['500万韩元以下', '500万–2000万韩元', '2000万–5000万韩元', '5000万韩元以上', '面议'] },
              { label: '咨询内容' },
            ],
          },
          media: {
            title: '媒体申请',
            description: '采访、拍摄、专访、转播与内容制作相关的媒体登记与合作申请。',
            cta: '媒体申请',
            pending: '申请受理正在准备中。',
            fields: [
              { label: '媒体/公司名称' },
              { label: '负责人姓名' },
              { label: '邮箱' },
              { label: '联系电话' },
              { label: '媒体类型', options: ['新闻报道', '电视转播', '油管/创作者', '摄影', '其他'] },
              { label: '采访目的' },
              { label: '是否拍摄', options: ['拍摄', '不拍摄', '待定'] },
              { label: '目标赛事' },
              { label: '需求内容' },
            ],
          },
          sponsor: {
            title: '赞助 / 合作',
            description: '面向与KSOP共创品牌体验的企业、品牌与合作伙伴的合作咨询。',
            cta: '合作咨询',
            pending: '申请受理正在准备中。',
            fields: [
              { label: '公司名称' },
              { label: '品牌名称' },
              { label: '负责人' },
              { label: '邮箱' },
              { label: '联系电话' },
              { label: '赞助类型', options: ['现金赞助', '产品赞助', '服务赞助', '组合赞助'] },
              { label: '现金/产品/服务区分' },
              { label: '目标赛事' },
              { label: '提案内容' },
            ],
          },
        },
      },
    },
  },
}

export type DetailSection = 'schedule' | 'event' | 'ranking' | 'news' | 'about'

export interface DetailLocaleContent {
  kicker: string
  title: string
  intro: string
}

/** Per-language hero copy for standalone detail pages. Items stay in English (official proper nouns). */
export const detailCopy: Record<Language, Record<DetailSection, DetailLocaleContent>> = {
  EN: {
    schedule: { kicker: '01 / SCHEDULE', title: 'SCHEDULE', intro: 'A considered calendar of live poker, from opening tables to championship nights.' },
    event: { kicker: 'EVENT / THE PROGRAM', title: 'THE TABLE IS SET', intro: 'Every event is built around momentum, precision, and the players who shape the room.' },
    ranking: { kicker: '03 / PLAYER RANKING', title: 'TOP PLAYERS', intro: 'The season belongs to the players who make every decision count.' },
    news: { kicker: '04 / FROM THE SERIES', title: 'INSIDE THE STORY.', intro: 'Reports, portraits, and moments from the Korea Series of Poker.' },
    about: { kicker: '01 / THE SERIES', title: 'MORE THAN A TOURNAMENT.', intro: "KSOP is a meeting place for Korea's sharpest minds, boldest plays, and most unforgettable stories." },
  },
  KR: {
    schedule: { kicker: '01 / 일정', title: '일정', intro: '오프닝 테이블부터 챔피언십의 밤까지, 신중하게 구성된 라이브 포커 캘린더.' },
    event: { kicker: '이벤트 / 프로그램', title: '테이블이 준비되었습니다', intro: '모든 이벤트는 흐름과 정밀함, 그리고 현장을 만들어가는 플레이어를 중심으로 설계됩니다.' },
    ranking: { kicker: '03 / 선수 랭킹', title: '탑 플레이어', intro: '매 결정이 중요한 선수들이 이번 시즌의 주인공입니다.' },
    news: { kicker: '04 / 시리즈 소식', title: '시리즈의 이야기.', intro: '코리아 시리즈 오브 포커의 현장 리포트, 인물, 순간들.' },
    about: { kicker: '01 / 시리즈', title: '토너먼트를 넘어서.', intro: 'KSOP는 한국 최고의 지성, 대담한 플레이, 잊을 수 없는 스토리가 만나는 곳입니다.' },
  },
  JP: {
    schedule: { kicker: '01 / スケジュール', title: 'スケジュール', intro: 'オープニングテーブルからチャンピオンシップナイトまで、練り上げられたライブポーカーカレンダー。' },
    event: { kicker: 'イベント / プログラム', title: 'テーブルは整った', intro: 'すべてのイベントは、勢いと精密さ、そして場を形作るプレイヤーを中心に設計されています。' },
    ranking: { kicker: '03 / プレイヤーランキング', title: 'トッププレイヤー', intro: '一つひとつの判断を大切にする選手たちが、このシーズンの主役です。' },
    news: { kicker: '04 / シリーズより', title: 'シリーズの物語。', intro: 'コリアシリーズオブポーカーの現場レポート、人物、瞬間。' },
    about: { kicker: '01 / シリーズ', title: 'トーナメントを超えて。', intro: 'KSOPは、韓国の鋭い頭脳、大胆なプレイ、忘れられない物語が出会う場所です。' },
  },
  CN: {
    schedule: { kicker: '01 / 赛程', title: '赛程', intro: '从开幕桌到冠军之夜，经过精心编排的现场扑克赛历。' },
    event: { kicker: '赛事 / 赛制', title: '牌桌已经摆好', intro: '每一场赛事都围绕节奏、精准以及塑造赛场的选手而打造。' },
    ranking: { kicker: '03 / 选手排名', title: '顶尖选手', intro: '属于那些让每个决定都有分量的选手的赛季。' },
    news: { kicker: '04 / 系列动态', title: '系列故事。', intro: '韩国扑克系列赛的报道、人物与瞬间。' },
    about: { kicker: '01 / 系列赛', title: '超越锦标赛。', intro: 'KSOP是韩国最睿智的头脑、最大胆的打法和最难忘的故事的交汇之地。' },
  },
}
