import {NextResponse} from 'next/server'
import {unstable_cache,revalidateTag} from 'next/cache'
import {randomUUID} from 'crypto'
import {createAdminClient} from '@/lib/supabase-server'
import {isAdminAuthenticated} from '@/lib/auth'
import {resources,validateRecord,safeUrl} from '@/lib/motion-cms'
import defaults from '@/lib/motion-defaults.json'
const tag='ksop-motion-content'
const fail=(e:unknown,status=400)=>NextResponse.json({error:e instanceof Error?e.message:'요청을 처리하지 못했습니다.'},{status,headers:{'Cache-Control':'no-store'}})
const db=()=>{const c=createAdminClient();if(!c)throw Error('홈페이지 DB 연결을 확인하세요.');return c}
async function read(resource:string,p:Record<string,string>,admin:boolean){const c=db();if(resource==='settings'){const {data,error}=await c.from('site_settings').select('value,updated_at').eq('key','motion:settings').maybeSingle();if(error)throw error;return {data:{...defaults,...data?.value},revision:data?.updated_at||null}}
const spec=resources[resource];if(!spec)throw Error('항목을 확인하세요.');const page=Math.max(1,Math.min(100000,Math.floor(Number(p.page))||1)),limit=Math.max(1,Math.min(24,Math.floor(Number(p.limit))||24));let q:any;
if(spec.table){q=c.from(spec.table).select([...new Set(['id','updated_at',...spec.fields.map(f=>f.key)])].join(','),{count:'exact'});if(!admin)q=q.eq('status','published');if(p.status&&p.status!=='all'&&admin)q=q.eq('status',p.status);if(p.id)q=q.eq(/^[0-9a-f-]{36}$/i.test(p.id)?'id':'slug',p.id);if(p.q)q=q.ilike(resource==='players'?'name':resource==='results'?'event_name':'title','%'+p.q.replace(/[%,()\\]/g,' ').slice(0,100)+'%');if(resource==='events'&&p.series)q=q.eq('series_id',p.series);if(p.category&&p.category!=='all'&&resource==='news')q=q.eq('category',p.category);if(resource==='results'){if(!admin&&!p.player)throw Error('선수를 선택하세요.');if(p.player){if(!admin){const {data,error}=await c.from('players').select('id').eq('id',p.player).eq('status','published').maybeSingle();if(error)throw error;if(!data)return {items:[],total:0,page,pageSize:limit}}q=q.eq('player_id',p.player)}}if(resource==='series'&&['upcoming','past'].includes(p.phase))q=p.phase==='past'?q.lt('ends_at',new Date().toISOString()):q.gte('ends_at',new Date().toISOString());q=q.order(spec.order||'sort_order',{ascending:!spec.descending}).order('id')}
else{q=c.from('site_settings').select('key,value,updated_at',{count:'exact'}).like('key',`motion:${resource}:%`);if(!admin)q=q.eq('value->>status','published');if(admin&&p.status&&p.status!=='all')q=q.eq('value->>status',p.status);if(p.id)q=q.eq('key',`motion:${resource}:${p.id}`);if(p.q)q=q.ilike('value->>title','%'+p.q.replace(/[%,()\\]/g,' ').slice(0,100)+'%');if(p.category&&p.category!=='all')q=q.eq('value->>category',p.category);q=q.order('value->sort_order').order('key')}
const {data,error,count}=await q.range((page-1)*limit,page*limit-1);if(error)throw Error(error.message);return {items:spec.table?data:(data||[]).map((r:any)=>({...r.value,id:r.key.split(':').pop(),updated_at:r.updated_at})),total:count||0,page,pageSize:limit}}
const cached=unstable_cache((r:string,p:Record<string,string>)=>read(r,p,false),['motion-cms-v2'],{revalidate:15,tags:[tag]})
export async function GET(req:Request){try{const p=new URL(req.url).searchParams,admin=p.get('view')==='admin';if(admin&&!await isAdminAuthenticated())return fail(Error('로그인이 필요합니다.'),401);const params=Object.fromEntries(['page','limit','id','q','series','player','category','phase','status'].map(k=>[k,p.get(k)||'']));return NextResponse.json(await (admin?read(p.get('resource')||'settings',params,true):cached(p.get('resource')||'settings',params)),{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e,503)}}
export async function PUT(req:Request){try{const origin=req.headers.get('origin');if(!await isAdminAuthenticated()||(origin&&new URL(origin).host!==req.headers.get('host')))return fail(Error('로그인이 필요합니다.'),401);const text=await req.text();if(text.length>300000)return fail(Error('내용이 너무 큽니다.'),413);const body=JSON.parse(text),r=String(body.resource),c=db(),now=new Date().toISOString();let q:any;
if(r==='settings'){const value:any={};for(const k of ['assets','homeCopy','pages','social','contactEmail','youtube'])if(k in body.data)value[k]=body.data[k];if(value.contactEmail&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.contactEmail))throw Error('이메일을 확인하세요.');for(const v of Object.values(value.assets||{}))if(v&&!safeUrl(v))throw Error('이미지 주소를 확인하세요.');for(const s of value.social||[])if(s.url&&!safeUrl(s.url))throw Error('소셜 주소를 확인하세요.');if(value.youtube&&!safeUrl(value.youtube))throw Error('채널 주소를 확인하세요.');q=body.revision?c.from('site_settings').update({value,updated_at:now}).eq('key','motion:settings').eq('updated_at',body.revision):c.from('site_settings').insert({key:'motion:settings',value,updated_at:now})}
else{const spec=resources[r];if(!spec)throw Error('항목을 확인하세요.');const data=validateRecord(r,body.data||{}),id=body.id||randomUUID();if(!/^[0-9a-f-]{36}$/i.test(id))throw Error('항목 주소를 확인하세요.');if(body.id&&!body.revision)throw Error('새로 불러온 후 저장하세요.');if(r!=='results'){data.status=data.status||'draft';data.sort_order=data.sort_order||0;data.slug=data.slug||`${r}-${id.slice(0,8)}`}if(spec.table)q=body.id?c.from(spec.table).update({...data,updated_at:now}).eq('id',id).eq('updated_at',body.revision):c.from(spec.table).insert({...data,id});else{const key=`motion:${r}:${id}`;q=body.id?c.from('site_settings').update({value:data,updated_at:now}).eq('key',key).eq('updated_at',body.revision):c.from('site_settings').insert({key,value:data,updated_at:now})}}
const {data,error}=await q.select().maybeSingle();if(error?.code==='23505'||(!error&&!data))return fail(Error('다른 곳에서 변경되었습니다. 새로 불러온 뒤 저장하세요.'),409);if(error)throw Error(error.message);revalidateTag(tag,{expire:0});return NextResponse.json({ok:true,revision:data.updated_at})}catch(e){return fail(e)}}
